- name: install mariadb server on CentOS
  tags: db,mariadb,centos
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"  
- name: Start mariadb service on centos
  tags: db,mariadb,centos
  service:
    name: mariadb
    state: started 
    enabled: yes
  when: ansible_distribution == "CentOS"