---
- hosts: all
  become: true
  tasks:
    - name: update repo index
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"] and ansible_distribution_version == "20.04" 
    - name: add php support
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]
    - name: update repo index centos
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install apache2 package centos
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"    
    - name: add php support centos
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"