---
- hosts: all
  become: true
  tasks:
    - name: install updates (centos)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:
    - name: add apache2 and php support for web servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2 
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]



- hosts: db_server
  become: true
  tasks:
    - name: install mariadb server on CentOS
      tags: db,mariadb,centos
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"  
    - name: Start mariadb service on centos
      tags: db,mariadb,centos
      service:
        name: mariadb
        state: started 
        enabled: yes
      when: ansible_distribution == "CentOS"