---
- hosts: all
  become: true
  tasks:
    - name: install updates (centos)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:
    - name: add apache2 and php support for web servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2 
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: add apache2 support for centos
      tags: centos,httpd,apache
      yum: 
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"
    
    - name: start apache server httpd
      tags: apache,centos
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Change the file for httpd
      tags: file,httpd,apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somebody.com
      when: ansible_distribution == "CentOS"
      register: var_name
      
    - name: Restart the httpd service when change in file
      tags: httpd,centos
      service:
        name: httpd
        state: restarted
      when: var_name.changed

      



- hosts: db_server
  become: true
  tasks:
    - name: install mariadb server on CentOS
      tags: db,mariadb,centos
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"  
    - name: Start mariadb service on centos
      tags: db,mariadb,centos
      service:
        name: mariadb
        state: started 
        enabled: yes
      when: ansible_distribution == "CentOS"