---
- hosts: all
  become: true
  tasks:
    - name: install updates (centos)
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    - name: install updates (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:
    - name: add apache2 and php support for web servers
      apt:
        name:
          - apache2 
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]



- hosts: db_server
  become: true
  tasks:
    - name: install mariadb server on CentOS
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"  